name: latex workflow

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            coursework/coursework.tex
            eng_biblatex/coursework.tex
            slides/slides.tex
          work_in_root_file_dir: true
          latexmk_shell_escape: true
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            coursework/coursework.pdf
            slides/slides.pdf
  release:
      runs-on: ubuntu-20.04
      needs: [compile]
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: PDF
        - name: ls
          run: ls -la
        - name: ls coursework
          run: ls coursework -la
        - name: ls slides
          run: ls slides -la
        - uses: softprops/action-gh-release@v1
          if: ${{ github.ref_type == 'tag' }}
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: | 
              coursework/coursework.pdf
              slides/slides.pdf
